name: NPM Dev Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify a Node.js version
    - name: Install Dependencies
      run: npm install
    - name: Run Dev Build
      run: npm run dev
